spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 896999086639-ljlnvom5ur5t9ljt26e8moquksthq73o.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: https://localhost:8091/login/oauth2/code/google
            scope: profile, email
