spring:
 security:
  oauth2:
   client:
    registration:
     google:
      client-id: 1030221416987-tmt4jaulnksmr4ojtd1eio1m7j2ughvf.apps.googleusercontent.com
      client-secret: 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
      scope:
       - profile
       - email
      redirect-uri: http://localhost:8091/login/oauth2/code/google
     naver:
      client-id: omNLHZizFD6Otxpo7Jmj
      client-secret: iervPEGjID
      scope:
       - id
       - name
       - profile_image
       - email
      client-name: naver
      authorization-grant-type: authorization_code
      redirect-uri: http://localhost:8091/login/oauth2/code/naver
     github:
      client-id: 527091411d4502628f25
      client-secret: 20788e54a3077ac71a88e41f0a71036af4556d91
    provider:
     naver:
      authorization-uri: https://nid.naver.com/oauth2.0/authorize
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
      user-name-attribute: response