server:
  port: 8091
  file:
    storage:
      #      #Mac OS
      #      path: /Users/laku_mwa/resource/
      #      Windows OS
      path: C:\NakyeonInt\resources

spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    port: 587
    username: cnakyeon@gmail.com
    password: pptf ftcn otng rvvc
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
            required: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: trelloWeb
    password: 1234
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 50
      minimum-idle: 20
      idle-timeout: 10000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  thymeleaf:
    cache: true
    check-template-location: true
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
    mvc :
      static-path-pattern : "/static/**"
  security:
    user:
      name: user
      password: 1234
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml