spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1030221416987-tmt4jaulnksmr4ojtd1eio1m7j2ughvf.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
            redirect-uri: http://localhost:8091/login/oauth2/code/google

